version: 0.2
phases:
  install:
    commands:
      - "sudo apt install unzip -y"
      - "sudo wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip"
      - "sudo unzip terraform_1.0.5_linux_amd64.zip"
      - "sudo mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform plan
