version: 0.2
phases:
 install:
    commands:
      - mkdir /opt/terraform
      - cd /opt/terraform
      - wget https://releases.hashicorp.com/terraform/1.0.6/terraform_1.0.6_linux_amd64.zip
      - unzip terraform_1.0.6_linux_amd64.zip
      - sudo mv terraform /usr/local/bin
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform plan
